pipeline {
    agent any

    stages {
        stage('Initialize') {
            steps {
                cleanWs()
            }
        }
        stage('Get SCM') {
            steps {
                git "https://github.com/saleh2784/lab.git"
                sh "cat Jenkinsfile"
            }
        }
        // stage('docker clean-old-versions'){
        //     steps {
        //         sh "docker kill nodewebapp"
        //         sh "docker rm nodewebapp"
        //     }
        // }
        stage('docker build'){
            steps {
                sh "docker build -t nodewebapp . "
                sh "docker images"
            }
        }
        stage('docker Deploy'){
            steps {
                sh "docker run -itd --name nodewebapp -p 3000:3000 nodewebapp:latest &"  
            }
        }
    }   
}

